#!/usr/bin/env python3
"""Generate deterministic domain and skill navigation views."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "wiki"
COVERAGE = ROOT / "state" / "coverage.yaml"
PAGE_PLAN = ROOT / "state" / "page-plan.yaml"
GENERATED_NOTICE = "<!-- Generated by scripts/generate_navigation.py; do not edit manually. -->"
DOMAIN_ORDER = ["1", "2", "3", "4", "5"]
TYPE_ORDER = [
    "AWS Service",
    "AWS Feature",
    "Concept",
    "Comparison",
    "Decision Guide",
    "Troubleshooting Playbook",
    "Exam Trap",
    "Learning Path",
    "Practice Set",
    "Knowledge Gap",
]


def frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    result: dict[str, object] = {}
    for line in text[4:end].splitlines():
        if not line or line[0].isspace() or ":" not in line:
            continue
        key, raw = line.split(":", 1)
        raw = raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            try:
                result[key] = ast.literal_eval(raw)
            except (SyntaxError, ValueError):
                result[key] = [
                    value.strip().strip("'\"")
                    for value in raw[1:-1].split(",")
                    if value.strip()
                ]
        else:
            result[key] = raw.strip("'\"")
    return result


def coverage_statuses() -> dict[str, str]:
    text = COVERAGE.read_text(encoding="utf-8")
    matches = list(re.finditer(r'^  - id: "([^"]+)"$', text, re.MULTILINE))
    statuses: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.start():end]
        status = re.search(r"^    status: ([^\n]+)", block, re.MULTILINE)
        if status:
            statuses[match.group(1)] = status.group(1).strip()
    return statuses


def page_plan() -> list[dict[str, object]]:
    text = PAGE_PLAN.read_text(encoding="utf-8")
    matches = list(re.finditer(r'^  - path: "([^"]+)"$', text, re.MULTILINE))
    pages: list[dict[str, object]] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.start():end]
        page_type = re.search(r'^    type: "([^"]+)"', block, re.MULTILINE)
        status = re.search(r"^    status: ([^\n]+)", block, re.MULTILINE)
        ids = re.search(r"^    skill_ids: \[([^\]]*)\]", block, re.MULTILINE)
        pages.append(
            {
                "path": match.group(1),
                "type": page_type.group(1) if page_type else "",
                "status": status.group(1).strip() if status else "",
                "skill_ids": re.findall(r'"([^"]+)"', ids.group(1)) if ids else [],
            }
        )
    return pages


def load_model():
    statuses = coverage_statuses()
    skills: list[dict[str, str]] = []
    domain_names: dict[str, str] = {}

    for path in sorted((ROOT / "raw" / "skills").glob("*.md")):
        meta = frontmatter(path)
        skill_id = str(meta.get("skill_id", ""))
        domain_id = str(meta.get("domain_id", ""))
        if not skill_id or not domain_id:
            continue
        domain_names[domain_id] = str(meta.get("domain", f"Domain {domain_id}"))
        skills.append(
            {
                "id": skill_id,
                "domain": domain_id,
                "title": str(meta.get("title", path.stem)),
                "path": path.relative_to(ROOT).as_posix(),
                "status": statuses.get(skill_id, "unknown"),
            }
        )

    pages = page_plan()
    for page in pages:
        page_path = ROOT / str(page["path"])
        if page["status"] == "implemented" and page_path.exists():
            meta = frontmatter(page_path)
            page["title"] = str(meta.get("title", page_path.stem))
            page["domain_ids"] = [str(value) for value in meta.get("domain_ids", [])]
        else:
            page["title"] = page_path.stem.replace("-", " ").title()
            page["domain_ids"] = []

    return skills, pages, domain_names


def status_label(value: str) -> str:
    return value.replace("_", " ").capitalize()


def type_key(value: str):
    try:
        return TYPE_ORDER.index(value)
    except ValueError:
        return len(TYPE_ORDER)


def render_skill(skill: dict[str, str], pages: list[dict[str, object]], domain_name: str) -> str:
    implemented = sorted(
        (
            page
            for page in pages
            if page["status"] == "implemented" and skill["id"] in page["skill_ids"]
        ),
        key=lambda page: (type_key(str(page["type"])), str(page["path"])),
    )
    planned = sorted(
        (
            page
            for page in pages
            if page["status"] == "planned" and skill["id"] in page["skill_ids"]
        ),
        key=lambda page: (type_key(str(page["type"])), str(page["path"])),
    )

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Skill {skill['id']}: {skill['title']}",
        "",
        f"- **Domain:** [Domain {skill['domain']}: {domain_name}](../domains/domain-{skill['domain']}.md)",
        f"- **Coverage status:** {status_label(skill['status'])}",
        f"- **Immutable source:** [Open raw skill](../../{skill['path']})",
        "",
        "## Generated knowledge",
        "",
    ]

    if implemented:
        lines.extend(["| Type | Page |", "| --- | --- |"])
        for page in implemented:
            target = "../" + str(page["path"]).removeprefix("wiki/")
            lines.append(f"| {page['type']} | [{page['title']}]({target}) |")
    else:
        lines.append("No generated knowledge page is implemented for this skill yet.")

    lines.extend(["", "## Planned knowledge", ""])
    if planned:
        for page in planned:
            lines.append(f"- **{page['type']}:** <code>{page['path']}</code>")
    else:
        lines.append("No additional planned page is currently assigned to this skill.")

    lines.extend(
        [
            "",
            "## Processing state",
            "",
            "- [Semantic coverage record](../../state/coverage.yaml)",
            "- [Corpus page plan](../../state/page-plan.yaml)",
            "- [Processing manifest](../../state/manifest.yaml)",
            "",
            "This page is a generated navigation view. Coverage status remains authoritative in <code>state/coverage.yaml</code>.",
            "",
        ]
    )
    return "\n".join(lines)


def render_domain(
    domain_id: str,
    domain_name: str,
    skills: list[dict[str, str]],
    pages: list[dict[str, object]],
) -> str:
    domain_skills = sorted(
        (skill for skill in skills if skill["domain"] == domain_id),
        key=lambda skill: [int(part) for part in skill["id"].split(".")],
    )
    skill_ids = {skill["id"] for skill in domain_skills}
    implemented = sorted(
        (
            page
            for page in pages
            if page["status"] == "implemented" and domain_id in page["domain_ids"]
        ),
        key=lambda page: (type_key(str(page["type"])), str(page["path"])),
    )
    planned = sorted(
        (
            page
            for page in pages
            if page["status"] == "planned"
            and any(skill_id in skill_ids for skill_id in page["skill_ids"])
        ),
        key=lambda page: (type_key(str(page["type"])), str(page["path"])),
    )
    counts = Counter(skill["status"] for skill in domain_skills)

    lines = [
        GENERATED_NOTICE,
        "",
        f"# Domain {domain_id}: {domain_name}",
        "",
        f"This domain contains {len(domain_skills)} source skills and {len(implemented)} implemented generated pages.",
        "",
        "## Coverage summary",
        "",
    ]
    for status in ["validated", "needs_reconciliation", "planned"]:
        if counts[status]:
            lines.append(f"- **{status_label(status)}:** {counts[status]} skills")

    lines.extend(["", "## Skills", "", "| Skill | Title | Coverage |", "| --- | --- | --- |"])
    for skill in domain_skills:
        lines.append(
            f"| [{skill['id']}](../skills/{skill['id']}.md) | {skill['title']} | {status_label(skill['status'])} |"
        )

    lines.extend(["", "## Implemented knowledge", ""])
    if implemented:
        grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
        for page in implemented:
            grouped[str(page["type"])].append(page)
        for page_type in sorted(grouped, key=type_key):
            lines.extend([f"### {page_type}", ""])
            for page in grouped[page_type]:
                target = "../" + str(page["path"]).removeprefix("wiki/")
                lines.append(f"- [{page['title']}]({target})")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
    else:
        lines.append("No generated knowledge pages are implemented for this domain yet.")

    lines.extend(["", "## Planned knowledge", ""])
    if planned:
        grouped_planned: dict[str, list[dict[str, object]]] = defaultdict(list)
        for page in planned:
            grouped_planned[str(page["type"])].append(page)
        for page_type in sorted(grouped_planned, key=type_key):
            lines.extend([f"### {page_type}", ""])
            for page in grouped_planned[page_type]:
                lines.append(f"- <code>{page['path']}</code>")
            lines.append("")
        if lines[-1] == "":
            lines.pop()
    else:
        lines.append("No additional planned pages are assigned to this domain.")

    lines.extend(
        [
            "",
            "## State",
            "",
            "- [Semantic coverage](../../state/coverage.yaml)",
            "- [Corpus page plan](../../state/page-plan.yaml)",
            "",
            "Planned paths are intentionally plain text until their files exist.",
            "",
        ]
    )
    return "\n".join(lines)


def render_skill_index(skills: list[dict[str, str]], domain_names: dict[str, str]) -> str:
    lines = [GENERATED_NOTICE, "", "# Skills", ""]
    for domain_id in DOMAIN_ORDER:
        lines.extend(
            [
                f"## [Domain {domain_id}: {domain_names[domain_id]}](../domains/domain-{domain_id}.md)",
                "",
                "| Skill | Title | Coverage |",
                "| --- | --- | --- |",
            ]
        )
        domain_skills = sorted(
            (skill for skill in skills if skill["domain"] == domain_id),
            key=lambda skill: [int(part) for part in skill["id"].split(".")],
        )
        for skill in domain_skills:
            lines.append(
                f"| [{skill['id']}]({skill['id']}.md) | {skill['title']} | {status_label(skill['status'])} |"
            )
        lines.append("")
    return "\n".join(lines)


def render_domain_index(skills: list[dict[str, str]], pages, domain_names: dict[str, str]) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        "# Domains",
        "",
        "| Domain | Source skills | Implemented pages | Skill status |",
        "| --- | ---: | ---: | --- |",
    ]
    for domain_id in DOMAIN_ORDER:
        domain_skills = [skill for skill in skills if skill["domain"] == domain_id]
        implemented = [
            page
            for page in pages
            if page["status"] == "implemented" and domain_id in page["domain_ids"]
        ]
        counts = Counter(skill["status"] for skill in domain_skills)
        status = ", ".join(
            f"{count} {status_label(key).lower()}"
            for key, count in (
                ("validated", counts["validated"]),
                ("needs_reconciliation", counts["needs_reconciliation"]),
                ("planned", counts["planned"]),
            )
            if count
        )
        lines.append(
            f"| [Domain {domain_id}: {domain_names[domain_id]}](domain-{domain_id}.md) | "
            f"{len(domain_skills)} | {len(implemented)} | {status} |"
        )
    lines.append("")
    return "\n".join(lines)


def desired_files() -> dict[Path, str]:
    skills, pages, domain_names = load_model()
    desired: dict[Path, str] = {
        WIKI / "skills" / "index.md": render_skill_index(skills, domain_names),
        WIKI / "domains" / "index.md": render_domain_index(skills, pages, domain_names),
    }
    for skill in skills:
        desired[WIKI / "skills" / f"{skill['id']}.md"] = render_skill(
            skill, pages, domain_names[skill["domain"]]
        )
    for domain_id in DOMAIN_ORDER:
        desired[WIKI / "domains" / f"domain-{domain_id}.md"] = render_domain(
            domain_id, domain_names[domain_id], skills, pages
        )
    return desired


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    desired = desired_files()
    stale: list[str] = []

    for path, content in desired.items():
        content = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if stale:
        print("Stale or missing generated navigation:")
        print("\n".join(f"- {path}" for path in stale))
        return 1

    action = "verified" if args.check else "generated"
    print(f"OK: {action} {len(desired)} domain and skill navigation files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
